AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'
    - 'lib/ldap_resource.rb'

ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 160

MethodLength:
  CountComments: false  # count full line comments?
  Max: 20
